### ISSUE TITLE
Enable js

### ISSUE THREAD

**Issue by Rockson** [sampi/node-less-chokidar#13]
`
node-less-chokidar --include-path ./node_modules src/ -o src/ --js
`

`err { [Error: Inline JavaScript is not enabled. Is it set in your options?
`

I Couldn't enable inline js inside less
--js is not working

**Comment by Ragzzy-R** [comment]
Is the PR fix getting merged? its impossible for non ejected CRA apps to enable it. please merge it or provide a flag to change it

**Comment by Ragzzy-R** [comment]
just in case if anyone stumbled upon this issue, 

You can do the changes made in the commit of the PR fix in your \node_modules\node-less-chokidar\bin\node-less-chokidar` file yourself (its just couple of lines) and it works.

Here is the commit details

sampi/node-less-chokidar@934af23
