### ISSUE TITLE
--include-path not working

### ISSUE THREAD

**Issue by 01binary** [sampi/node-less-chokidar#3]
I installed this package for use with `create-react-app`, where they say you can specify `--include-path` option to import less modules from `node_modules` folder but it's not working. It's looking for the module in current directory.

**Comment by chad-codes** [comment]
`create-react-app`'s documentation uses `node-sass-chokidar` as an example. This version doesn't appear to support the `--include-path` option.

**Comment by kosssi** [comment]
This PR can resolve it https://github.com/sampi/node-less-chokidar/pull/7

**Comment by sampi** [comment]
Thanks for the help guys, I've merged the PR and released it with https://github.com/sampi/node-less-chokidar/releases/tag/v0.3.1 .

**Comment by kosssi** [comment]
thanks @sampi
