### ISSUE TITLE
Cannot disable the generations of source maps

### ISSUE THREAD

**Issue by OshotOkill** [sampi/node-less-chokidar#5]
I tend to use `node-less-chokidar src/ -o src/` in my project and it always generates the source map of each `.less` file. I tried to use `node-less-chokidar --source-map false src/ -o src` as well, while that doesn't work for me.

**Comment by sampi** [comment]
https://github.com/sampi/node-less-chokidar/releases/tag/v0.3.1 has a new flag to disable generating source maps.

`node-less-chokidar --skip-source-map src/`

The output will always be right next to the `.less` files, so you don't need to specify that.
