### ISSUE TITLE
Configurable compiler options

### ISSUE THREAD

**Issue by d07RiV** [sampi/node-less-chokidar#6]
Currently there seems to be no way to pass additional options to less compiler. For many projects, strict-math is mandatory to avoid breaking CSS3 `calc`, which is not possible to use with this module.

**Comment by d07RiV** [comment]
The --help text also gives the following example:

    node-less-chokidar --output-style compressed foobar.less > foobar.css

But I don't see any reference to `outputStyle` in the code, none of the options are forwarded to less render, and `outputStyle` doesn't seem to be a less option anyway.

**Comment by sampi** [comment]
https://github.com/sampi/node-less-chokidar/releases/tag/v0.3.1 is using LESS v3, this should help with the issues related to `calc()`.

Otherwise, you can always write it like this: 
```less
.rule {
  width: ~'calc(100vh - 4 * @{specialWidth})';
}
```
